version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=drug_indications_db
    ports:
      - "27017:27017"
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_URL=mongodb://root:rootpassword@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  pipeline:
    container_name: pipeline
    build:
      context: ./data-extractor
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app/data-extractor
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/drug_indications_db?authSource=admin
      - MONGODB_NAME=drug_indications_db
    command: ["python", "/app/data-extractor/pipeline.py"]

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    working_dir: /app/api
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  mongodb_data:
